Basic NLTK

In [1]:
import nltk

In [2]:
nltk.download('gutenberg')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
from nltk.corpus import gutenberg

In [4]:
gutenberg.words()

['[', 'Emma', 'by', 'Jane', 'Austen', '1816', ']', ...]

In [5]:
gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

# Q1 (1) File Method

In [17]:
import os
path = "E:/ML assignments/assign 1/corpus/"
filenames=os.listdir(path)
contents=[]
for i in range(len(filenames)):
    f=open(path+filenames[i],"r")
    text=f.read()
    contents.append(text)
    f.close()

In [19]:
contents

['However venture pursuit he am mr cordial. Forming musical am hearing studied be luckily. Ourselves for determine attending how led gentleman sincerity. Valley afford uneasy joy she thrown though bed set. In me forming general prudent on country carried. Behaved an or suppose justice. Seemed whence how son rather easily and change missed. Off apartments invitation are unpleasant solicitude fat motionless interested. Hardly suffer wisdom wishes valley as an. As friendship advantages resolution it alteration stimulated he or increasing. ',
 'Debating me breeding be answered an he. Spoil event was words her off cause any. Tears woman which no is world miles woody. Wished be do mutual except in effect answer. Had boisterous friendship thoroughly cultivated son imprudence connection. Windows because concern sex its. Law allow saved views hills day ten. Examine waiting his evening day passage proceed. \n\n',
 'Is branched in my up strictly remember. Songs but chief has ham widow downs. Geni

# Q1 (2) Inbuilt

In [20]:
from nltk.corpus import PlaintextCorpusReader 
dataset=PlaintextCorpusReader(path ,'.*')

In [21]:
dataset

<PlaintextCorpusReader in 'E:\\ML assignments\\assign 1\\corpus'>

In [25]:
dataset.fileids()

['1.txt',
 '10.txt',
 '2.txt',
 '3.txt',
 '4.txt',
 '5.txt',
 '6.txt',
 '7.txt',
 '8.txt',
 '9.txt']

In [27]:
dataset.raw()

'However venture pursuit he am mr cordial. Forming musical am hearing studied be luckily. Ourselves for determine attending how led gentleman sincerity. Valley afford uneasy joy she thrown though bed set. In me forming general prudent on country carried. Behaved an or suppose justice. Seemed whence how son rather easily and change missed. Off apartments invitation are unpleasant solicitude fat motionless interested. Hardly suffer wisdom wishes valley as an. As friendship advantages resolution it alteration stimulated he or increasing. Debating me breeding be answered an he. Spoil event was words her off cause any. Tears woman which no is world miles woody. Wished be do mutual except in effect answer. Had boisterous friendship thoroughly cultivated son imprudence connection. Windows because concern sex its. Law allow saved views hills day ten. Examine waiting his evening day passage proceed. \r\n\r\nIs branched in my up strictly remember. Songs but chief has ham widow downs. Genius or s

In [28]:
dataset.sents()

[['However', 'venture', 'pursuit', 'he', 'am', 'mr', 'cordial', '.'], ['Forming', 'musical', 'am', 'hearing', 'studied', 'be', 'luckily', '.'], ...]

In [29]:
dataset.words()

['However', 'venture', 'pursuit', 'he', 'am', 'mr', ...]

# Q2  normalization, tokenization, stopword removal, stemming

In [31]:
# Normalization
corpus = contents 
lower_corpus=[] 
print(corpus)
for i in range(len(corpus)):
    lower_corpus.append(' '.join([word.lower() for word in corpus[i].split()])) 
print(lower_corpus)

['However venture pursuit he am mr cordial. Forming musical am hearing studied be luckily. Ourselves for determine attending how led gentleman sincerity. Valley afford uneasy joy she thrown though bed set. In me forming general prudent on country carried. Behaved an or suppose justice. Seemed whence how son rather easily and change missed. Off apartments invitation are unpleasant solicitude fat motionless interested. Hardly suffer wisdom wishes valley as an. As friendship advantages resolution it alteration stimulated he or increasing. ', 'Debating me breeding be answered an he. Spoil event was words her off cause any. Tears woman which no is world miles woody. Wished be do mutual except in effect answer. Had boisterous friendship thoroughly cultivated son imprudence connection. Windows because concern sex its. Law allow saved views hills day ten. Examine waiting his evening day passage proceed. \n\n', 'Is branched in my up strictly remember. Songs but chief has ham widow downs. Genius

In [36]:
# tokenization
from nltk.tokenize import word_tokenize
tokenized_corpus = []
for i in range(len(lower_corpus)):
    tokenized_corpus.append(word_tokenize(lower_corpus[i]))

print(tokenized_corpus) 

[['however', 'venture', 'pursuit', 'he', 'am', 'mr', 'cordial', '.', 'forming', 'musical', 'am', 'hearing', 'studied', 'be', 'luckily', '.', 'ourselves', 'for', 'determine', 'attending', 'how', 'led', 'gentleman', 'sincerity', '.', 'valley', 'afford', 'uneasy', 'joy', 'she', 'thrown', 'though', 'bed', 'set', '.', 'in', 'me', 'forming', 'general', 'prudent', 'on', 'country', 'carried', '.', 'behaved', 'an', 'or', 'suppose', 'justice', '.', 'seemed', 'whence', 'how', 'son', 'rather', 'easily', 'and', 'change', 'missed', '.', 'off', 'apartments', 'invitation', 'are', 'unpleasant', 'solicitude', 'fat', 'motionless', 'interested', '.', 'hardly', 'suffer', 'wisdom', 'wishes', 'valley', 'as', 'an', '.', 'as', 'friendship', 'advantages', 'resolution', 'it', 'alteration', 'stimulated', 'he', 'or', 'increasing', '.'], ['debating', 'me', 'breeding', 'be', 'answered', 'an', 'he', '.', 'spoil', 'event', 'was', 'words', 'her', 'off', 'cause', 'any', '.', 'tears', 'woman', 'which', 'no', 'is', 'world

In [37]:
# stopwords removal
from nltk.corpus import stopwords
stop=stopwords.words(fileids='english')
tokenized_corpus_nostop=[]
for i in range(len(tokenized_corpus)):
      tokenized_corpus_nostop.append([word for word in tokenized_corpus[i] if word not in stop])
        

In [38]:
tokenized_corpus_nostop

[['however',
  'venture',
  'pursuit',
  'mr',
  'cordial',
  '.',
  'forming',
  'musical',
  'hearing',
  'studied',
  'luckily',
  '.',
  'determine',
  'attending',
  'led',
  'gentleman',
  'sincerity',
  '.',
  'valley',
  'afford',
  'uneasy',
  'joy',
  'thrown',
  'though',
  'bed',
  'set',
  '.',
  'forming',
  'general',
  'prudent',
  'country',
  'carried',
  '.',
  'behaved',
  'suppose',
  'justice',
  '.',
  'seemed',
  'whence',
  'son',
  'rather',
  'easily',
  'change',
  'missed',
  '.',
  'apartments',
  'invitation',
  'unpleasant',
  'solicitude',
  'fat',
  'motionless',
  'interested',
  '.',
  'hardly',
  'suffer',
  'wisdom',
  'wishes',
  'valley',
  '.',
  'friendship',
  'advantages',
  'resolution',
  'alteration',
  'stimulated',
  'increasing',
  '.'],
 ['debating',
  'breeding',
  'answered',
  '.',
  'spoil',
  'event',
  'words',
  'cause',
  '.',
  'tears',
  'woman',
  'world',
  'miles',
  'woody',
  '.',
  'wished',
  'mutual',
  'except',
  'e

In [39]:
# stemming
from nltk.stem import PorterStemmer

ps = PorterStemmer()

tokenized_corpus_nostop_stem=[]

for i in range (len(tokenized_corpus_nostop)):
    tokenized_corpus_nostop_stem.append([ps.stem(word) for word in tokenized_corpus_nostop[i]])

print (tokenized_corpus_nostop_stem)

[['howev', 'ventur', 'pursuit', 'mr', 'cordial', '.', 'form', 'music', 'hear', 'studi', 'luckili', '.', 'determin', 'attend', 'led', 'gentleman', 'sincer', '.', 'valley', 'afford', 'uneasi', 'joy', 'thrown', 'though', 'bed', 'set', '.', 'form', 'gener', 'prudent', 'countri', 'carri', '.', 'behav', 'suppos', 'justic', '.', 'seem', 'whenc', 'son', 'rather', 'easili', 'chang', 'miss', '.', 'apart', 'invit', 'unpleas', 'solicitud', 'fat', 'motionless', 'interest', '.', 'hardli', 'suffer', 'wisdom', 'wish', 'valley', '.', 'friendship', 'advantag', 'resolut', 'alter', 'stimul', 'increas', '.'], ['debat', 'breed', 'answer', '.', 'spoil', 'event', 'word', 'caus', '.', 'tear', 'woman', 'world', 'mile', 'woodi', '.', 'wish', 'mutual', 'except', 'effect', 'answer', '.', 'boister', 'friendship', 'thoroughli', 'cultiv', 'son', 'imprud', 'connect', '.', 'window', 'concern', 'sex', '.', 'law', 'allow', 'save', 'view', 'hill', 'day', 'ten', '.', 'examin', 'wait', 'even', 'day', 'passag', 'proceed', '.

In [44]:
# lemmatization
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
tokenized_corpus_nostop_lemmatized=[]
for i in range(len(tokenized_corpus_nostop)):
    tokenized_corpus_nostop_lemmatized.append([lemmatizer.lemmatize(word) for word in tokenized_corpus_nostop[i]])
print(tokenized_corpus_nostop_lemmatized)

[['however', 'venture', 'pursuit', 'mr', 'cordial', '.', 'forming', 'musical', 'hearing', 'studied', 'luckily', '.', 'determine', 'attending', 'led', 'gentleman', 'sincerity', '.', 'valley', 'afford', 'uneasy', 'joy', 'thrown', 'though', 'bed', 'set', '.', 'forming', 'general', 'prudent', 'country', 'carried', '.', 'behaved', 'suppose', 'justice', '.', 'seemed', 'whence', 'son', 'rather', 'easily', 'change', 'missed', '.', 'apartment', 'invitation', 'unpleasant', 'solicitude', 'fat', 'motionless', 'interested', '.', 'hardly', 'suffer', 'wisdom', 'wish', 'valley', '.', 'friendship', 'advantage', 'resolution', 'alteration', 'stimulated', 'increasing', '.'], ['debating', 'breeding', 'answered', '.', 'spoil', 'event', 'word', 'cause', '.', 'tear', 'woman', 'world', 'mile', 'woody', '.', 'wished', 'mutual', 'except', 'effect', 'answer', '.', 'boisterous', 'friendship', 'thoroughly', 'cultivated', 'son', 'imprudence', 'connection', '.', 'window', 'concern', 'sex', '.', 'law', 'allow', 'saved

In [54]:
# cleaned corpus obtained after pre-processing 
cleaned_corpus = []
for i in range(len(tokenized_corpus_nostop_lemmatized)):
    cleaned_corpus.append(' '.join([word for word in tokenized_corpus_nostop_lemmatized[i]])) 
cleaned_corpus                         

['however venture pursuit mr cordial . forming musical hearing studied luckily . determine attending led gentleman sincerity . valley afford uneasy joy thrown though bed set . forming general prudent country carried . behaved suppose justice . seemed whence son rather easily change missed . apartment invitation unpleasant solicitude fat motionless interested . hardly suffer wisdom wish valley . friendship advantage resolution alteration stimulated increasing .',
 'debating breeding answered . spoil event word cause . tear woman world mile woody . wished mutual except effect answer . boisterous friendship thoroughly cultivated son imprudence connection . window concern sex . law allow saved view hill day ten . examine waiting evening day passage proceed .',
 'branched strictly remember . song chief ham widow down . genius vanity . large tried going water defer . silent son man wished mother . distrust allowance knowledge eagerness assurance addition .',
 'necessary ye contented newspape

In [55]:
# Bag of Words matrix using CountVectorizer() import sklearn
from sklearn.feature_extraction.text import CountVectorizer 
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(cleaned_corpus) 
print(vectorizer.get_feature_names()) 
print(x.toarray())

['acuteness', 'add', 'addition', 'admitted', 'advantage', 'advice', 'afford', 'age', 'agreeable', 'allow', 'allowance', 'alteration', 'although', 'another', 'answer', 'answered', 'apartment', 'appearance', 'article', 'assurance', 'astonished', 'attempt', 'attempted', 'attending', 'aware', 'barton', 'bed', 'behaved', 'behaviour', 'believe', 'believed', 'beloved', 'besides', 'body', 'boisterous', 'boy', 'branched', 'breakfast', 'breeding', 'carried', 'cause', 'chamber', 'change', 'charmed', 'chicken', 'chief', 'civilly', 'comfort', 'concealed', 'concern', 'concluded', 'connection', 'contempt', 'contented', 'continual', 'conveying', 'cordial', 'cordially', 'cottage', 'country', 'county', 'course', 'cultivated', 'dashwood', 'day', 'debating', 'decisively', 'defer', 'delay', 'demesne', 'depending', 'desirous', 'determine', 'detract', 'distrust', 'domestic', 'down', 'eagerness', 'earnestly', 'easily', 'education', 'effect', 'either', 'elinor', 'engaged', 'enjoyed', 'enjoyment', 'equally', 'e

# q3 (a)

In [56]:
# Bag of Words matrix using CountVectorizer() import sklearn
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(cleaned_corpus) 
print(vectorizer.get_feature_names()) 
print(x.toarray())

['acuteness', 'add', 'addition', 'admitted', 'advantage', 'advice', 'afford', 'age', 'agreeable', 'allow', 'allowance', 'alteration', 'although', 'another', 'answer', 'answered', 'apartment', 'appearance', 'article', 'assurance', 'astonished', 'attempt', 'attempted', 'attending', 'aware', 'barton', 'bed', 'behaved', 'behaviour', 'believe', 'believed', 'beloved', 'besides', 'body', 'boisterous', 'boy', 'branched', 'breakfast', 'breeding', 'carried', 'cause', 'chamber', 'change', 'charmed', 'chicken', 'chief', 'civilly', 'comfort', 'concealed', 'concern', 'concluded', 'connection', 'contempt', 'contented', 'continual', 'conveying', 'cordial', 'cordially', 'cottage', 'country', 'county', 'course', 'cultivated', 'dashwood', 'day', 'debating', 'decisively', 'defer', 'delay', 'demesne', 'depending', 'desirous', 'determine', 'detract', 'distrust', 'domestic', 'down', 'eagerness', 'earnestly', 'easily', 'education', 'effect', 'either', 'elinor', 'engaged', 'enjoyed', 'enjoyment', 'equally', 'e

In [57]:
# tfidf matrix using TfidfVectorizer()
from sklearn.feature_extraction.text import TfidfVectorizer 
tfidfvectorizer = TfidfVectorizer()
X = tfidfvectorizer.fit_transform(cleaned_corpus)
print(tfidfvectorizer.get_feature_names())
print(X.toarray())

['acuteness', 'add', 'addition', 'admitted', 'advantage', 'advice', 'afford', 'age', 'agreeable', 'allow', 'allowance', 'alteration', 'although', 'another', 'answer', 'answered', 'apartment', 'appearance', 'article', 'assurance', 'astonished', 'attempt', 'attempted', 'attending', 'aware', 'barton', 'bed', 'behaved', 'behaviour', 'believe', 'believed', 'beloved', 'besides', 'body', 'boisterous', 'boy', 'branched', 'breakfast', 'breeding', 'carried', 'cause', 'chamber', 'change', 'charmed', 'chicken', 'chief', 'civilly', 'comfort', 'concealed', 'concern', 'concluded', 'connection', 'contempt', 'contented', 'continual', 'conveying', 'cordial', 'cordially', 'cottage', 'country', 'county', 'course', 'cultivated', 'dashwood', 'day', 'debating', 'decisively', 'defer', 'delay', 'demesne', 'depending', 'desirous', 'determine', 'detract', 'distrust', 'domestic', 'down', 'eagerness', 'earnestly', 'easily', 'education', 'effect', 'either', 'elinor', 'engaged', 'enjoyed', 'enjoyment', 'equally', 'e

# q3 (b)

In [59]:
features = []
for i in range(len(cleaned_corpus)):
    for word in cleaned_corpus[i].split():
        if word not in features:
            features.append(word)
features.sort()
print(len(features))
print(features)

283
['.', 'acuteness', 'add', 'addition', 'admitted', 'advantage', 'advice', 'afford', 'age', 'agreeable', 'allow', 'allowance', 'alteration', 'although', 'another', 'answer', 'answered', 'apartment', 'appearance', 'article', 'assurance', 'astonished', 'attempt', 'attempted', 'attending', 'aware', 'barton', 'bed', 'behaved', 'behaviour', 'believe', 'believed', 'beloved', 'besides', 'body', 'boisterous', 'boy', 'branched', 'breakfast', 'breeding', 'carried', 'cause', 'chamber', 'change', 'charmed', 'chicken', 'chief', 'civilly', 'comfort', 'concealed', 'concern', 'concluded', 'connection', 'contempt', 'contented', 'continual', 'conveying', 'cordial', 'cordially', 'cottage', 'country', 'county', 'course', 'cultivated', 'dashwood', 'day', 'debating', 'decisively', 'defer', 'delay', 'demesne', 'depending', 'desirous', 'determine', 'detract', 'distrust', 'domestic', 'down', 'eagerness', 'earnestly', 'easily', 'education', 'effect', 'either', 'elinor', 'engaged', 'enjoyed', 'enjoyment', 'equ

In [61]:
# Bag of words without using inbuilt function 
import numpy as np
bow = np.zeros((len(cleaned_corpus), len(features)))
for i in range(len(cleaned_corpus)):
    for j in range(len(features)):
        bow[i][j] = cleaned_corpus[i].split().count(features[j])
print(bow)

[[10.  0.  0. ...  0.  0.  0.]
 [ 8.  0.  0. ...  0.  0.  0.]
 [ 6.  0.  0. ...  0.  0.  0.]
 ...
 [ 7.  0.  1. ...  0.  1.  0.]
 [ 7.  0.  1. ...  0.  1.  0.]
 [ 6.  0.  1. ...  0.  0.  0.]]


In [62]:
# calculating idf matrix
idf = np.zeros(len(features))
df = np.zeros(len(features))
n = len(cleaned_corpus)
for i in range(len(features)):
    df[i] = 0
    for j in range(len(cleaned_corpus)):
        if features[i] in cleaned_corpus[j].split():
            df[i] += 1
    idf[i] = np.log((1+n)/(1+df[i])) + 1
print(len(idf))
print(idf)

283
[1.         2.70474809 1.6061358  2.29928298 2.70474809 2.70474809
 2.70474809 2.70474809 2.29928298 2.29928298 2.29928298 2.70474809
 2.29928298 2.29928298 2.70474809 2.29928298 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.29928298 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.29928298 2.70474809 2.29928298 2.29928298 2.70474809
 2.70474809 2.29928298 2.70474809 2.29928298 2.70474809 2.70474809
 2.29928298 2.29928298 2.70474809 2.70474809 2.70474809 2.29928298
 2.29928298 2.29928298 2.70474809 2.70474809 2.29928298 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.29928298 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.29928298
 2.70474809 2.70474809 2.29928298 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.29928298 2.70474809 2.70474809 2.70474809
 2.29928298 2.70474809 2.70474809 2.29928298 2.70474809 2.

In [63]:
# calculating tfidf matrix 
tfidf = np.multiply(bow, idf) 
print(tfidf)

[[10.          0.          0.         ...  0.          0.
   0.        ]
 [ 8.          0.          0.         ...  0.          0.
   0.        ]
 [ 6.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 7.          0.          1.6061358  ...  0.          2.29928298
   0.        ]
 [ 7.          0.          1.6061358  ...  0.          2.29928298
   0.        ]
 [ 6.          0.          1.6061358  ...  0.          0.
   0.        ]]


In [64]:
# tfidf matrix using TfidfVectorizer() for comparison
from sklearn.feature_extraction.text import TfidfVectorizer 
tfidfvectorizer = TfidfVectorizer()
X = tfidfvectorizer.fit_transform(cleaned_corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['acuteness', 'add', 'addition', 'admitted', 'advantage', 'advice', 'afford', 'age', 'agreeable', 'allow', 'allowance', 'alteration', 'although', 'another', 'answer', 'answered', 'apartment', 'appearance', 'article', 'assurance', 'astonished', 'attempt', 'attempted', 'attending', 'aware', 'barton', 'bed', 'behaved', 'behaviour', 'believe', 'believed', 'beloved', 'besides', 'body', 'boisterous', 'boy', 'branched', 'breakfast', 'breeding', 'carried', 'cause', 'chamber', 'change', 'charmed', 'chicken', 'chief', 'civilly', 'comfort', 'concealed', 'concern', 'concluded', 'connection', 'contempt', 'contented', 'continual', 'conveying', 'cordial', 'cordially', 'cottage', 'country', 'county', 'course', 'cultivated', 'dashwood', 'day', 'debating', 'decisively', 'defer', 'delay', 'demesne', 'depending', 'desirous', 'determine', 'detract', 'distrust', 'domestic', 'down', 'eagerness', 'earnestly', 'easily', 'education', 'effect', 'either', 'elinor', 'engaged', 'enjoyed', 'enjoyment', 'equally', 'e

# q4

In [10]:
html = ["""
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> <style>
</style>
</head>
<body>
<p>The function <code>selectAll()</code> highlights all the text in the input field so the user can, for example, copy or delete the text.</p> <h1>My Bad</h1>
<p>can't find anything better.</p>
How can I be this silly, but it doesn't matter anyway, Hahah
</body>
</html>
""","""
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> <style>
</style>
</head>
<body>
<p>The function <code>selectAll()</code> highlights all the text in the input field so the user can, for example, copy or delete the text.</p> <h1>My Bad</h1>
<p>can't find anything better.</p>
How can I be this silly, but it doesn't matter anyway, Hahah
</body>
</html>
""","""
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> <style>
</style>
</head>
<body>
<p>The function <code>selectAll()</code> highlights all the text in the input field so the user can, for example, copy or delete the text.</p> <h1>My Bad</h1>
<p>can't find anything better.</p>
How can I be this silly, but it doesn't matter anyway, Hahah
</body>
</html>
"""]

In [14]:
import bs4
from bs4 import BeautifulSoup
data = []
for i in range(len(html)):
    soup = BeautifulSoup(html[i], 'html.parser')
    data.append(soup.get_text())
data

["\n\n\n\nPage Title\n\n \n\n\nThe function selectAll() highlights all the text in the input field so the user can, for example, copy or delete the text. My Bad\ncan't find anything better.\nHow can I be this silly, but it doesn't matter anyway, Hahah\n\n\n",
 "\n\n\n\nPage Title\n\n \n\n\nThe function selectAll() highlights all the text in the input field so the user can, for example, copy or delete the text. My Bad\ncan't find anything better.\nHow can I be this silly, but it doesn't matter anyway, Hahah\n\n\n",
 "\n\n\n\nPage Title\n\n \n\n\nThe function selectAll() highlights all the text in the input field so the user can, for example, copy or delete the text. My Bad\ncan't find anything better.\nHow can I be this silly, but it doesn't matter anyway, Hahah\n\n\n"]

In [15]:
# Normalization
corpus = data
lower_corpus=[] 
print(corpus)
for i in range(len(corpus)):
    lower_corpus.append(' '.join([word.lower() for word in corpus[i].split()]))
print(lower_corpus)

["\n\n\n\nPage Title\n\n \n\n\nThe function selectAll() highlights all the text in the input field so the user can, for example, copy or delete the text. My Bad\ncan't find anything better.\nHow can I be this silly, but it doesn't matter anyway, Hahah\n\n\n", "\n\n\n\nPage Title\n\n \n\n\nThe function selectAll() highlights all the text in the input field so the user can, for example, copy or delete the text. My Bad\ncan't find anything better.\nHow can I be this silly, but it doesn't matter anyway, Hahah\n\n\n", "\n\n\n\nPage Title\n\n \n\n\nThe function selectAll() highlights all the text in the input field so the user can, for example, copy or delete the text. My Bad\ncan't find anything better.\nHow can I be this silly, but it doesn't matter anyway, Hahah\n\n\n"]
["page title the function selectall() highlights all the text in the input field so the user can, for example, copy or delete the text. my bad can't find anything better. how can i be this silly, but it doesn't matter anyw

In [16]:
# tokenization
from nltk.tokenize import word_tokenize
tokenized_corpus=[]
for i in range(len(lower_corpus)):
    tokenized_corpus.append([word for word in word_tokenize(lower_corpus[i]) ])
print(tokenized_corpus)

[['page', 'title', 'the', 'function', 'selectall', '(', ')', 'highlights', 'all', 'the', 'text', 'in', 'the', 'input', 'field', 'so', 'the', 'user', 'can', ',', 'for', 'example', ',', 'copy', 'or', 'delete', 'the', 'text', '.', 'my', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'how', 'can', 'i', 'be', 'this', 'silly', ',', 'but', 'it', 'does', "n't", 'matter', 'anyway', ',', 'hahah'], ['page', 'title', 'the', 'function', 'selectall', '(', ')', 'highlights', 'all', 'the', 'text', 'in', 'the', 'input', 'field', 'so', 'the', 'user', 'can', ',', 'for', 'example', ',', 'copy', 'or', 'delete', 'the', 'text', '.', 'my', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'how', 'can', 'i', 'be', 'this', 'silly', ',', 'but', 'it', 'does', "n't", 'matter', 'anyway', ',', 'hahah'], ['page', 'title', 'the', 'function', 'selectall', '(', ')', 'highlights', 'all', 'the', 'text', 'in', 'the', 'input', 'field', 'so', 'the', 'user', 'can', ',', 'for', 'example', ',', 'copy', 'or', 'delet

In [17]:
# stopwords removal
from nltk.corpus import stopwords
stop=stopwords.words(fileids='english')
tokenized_corpus_nostop=[]
for i in range(len(tokenized_corpus)):
    tokenized_corpus_nostop.append([word for word in tokenized_corpus[i] if word not in stop])
print(tokenized_corpus_nostop)

[['page', 'title', 'function', 'selectall', '(', ')', 'highlights', 'text', 'input', 'field', 'user', ',', 'example', ',', 'copy', 'delete', 'text', '.', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'silly', ',', "n't", 'matter', 'anyway', ',', 'hahah'], ['page', 'title', 'function', 'selectall', '(', ')', 'highlights', 'text', 'input', 'field', 'user', ',', 'example', ',', 'copy', 'delete', 'text', '.', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'silly', ',', "n't", 'matter', 'anyway', ',', 'hahah'], ['page', 'title', 'function', 'selectall', '(', ')', 'highlights', 'text', 'input', 'field', 'user', ',', 'example', ',', 'copy', 'delete', 'text', '.', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'silly', ',', "n't", 'matter', 'anyway', ',', 'hahah']]


In [19]:
# lemmatization
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
tokenized_corpus_nostop_lemmatized=[]
for i in range(len(tokenized_corpus_nostop)):
    tokenized_corpus_nostop_lemmatized.append([lemmatizer.lemmatize(word) for word in tokenized_corpus_nostop[i]])
print(tokenized_corpus_nostop_lemmatized)

[['page', 'title', 'function', 'selectall', '(', ')', 'highlight', 'text', 'input', 'field', 'user', ',', 'example', ',', 'copy', 'delete', 'text', '.', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'silly', ',', "n't", 'matter', 'anyway', ',', 'hahah'], ['page', 'title', 'function', 'selectall', '(', ')', 'highlight', 'text', 'input', 'field', 'user', ',', 'example', ',', 'copy', 'delete', 'text', '.', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'silly', ',', "n't", 'matter', 'anyway', ',', 'hahah'], ['page', 'title', 'function', 'selectall', '(', ')', 'highlight', 'text', 'input', 'field', 'user', ',', 'example', ',', 'copy', 'delete', 'text', '.', 'bad', 'ca', "n't", 'find', 'anything', 'better', '.', 'silly', ',', "n't", 'matter', 'anyway', ',', 'hahah']]


In [21]:
# creating feature vector
features = []
for i in range(len(tokenized_corpus_nostop_lemmatized)): 
    for word in tokenized_corpus_nostop_lemmatized[i]:

        if word not in features: 
            features.append(word)
features.sort()
print(len(features))
print(features)

26
['(', ')', ',', '.', 'anything', 'anyway', 'bad', 'better', 'ca', 'copy', 'delete', 'example', 'field', 'find', 'function', 'hahah', 'highlight', 'input', 'matter', "n't", 'page', 'selectall', 'silly', 'text', 'title', 'user']
